# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://docs.hugoblox.com/reference/language/

# Default language
en:
  languageCode: en-us
  languageName: "🇬🇧 English"
  # Uncomment for multi-lingual sites, and move English content into `en` sub-folder.
  #contentDir: content/en
  menu:
    main:
      - name: News
        url: post
        weight: 20
      - name: People
        url: people
        weight: 30
      - name: Lab-Software
        url: project
        weight: 40
      - name: Posters-Slides
        url: posters
        weight: 50
      - name: Publications
        url: publication
        weight: 60
      - name: Projects
        url: fondecyts
        weight: 70
      - name: Location
        url: location
        weight: 80

# Spanish language
es:
  languageCode: es
  languageName: "🇨🇱 Español"
  title: Laboratorio de Meshing para Ciencia Aplicada (+Lab)
  params:
    description: El laboratorio +Lab del Departamento de Ciencias de la Computación de la Universidad de Chile se dedica al estudio y desarrollo de algoritmos y herramientas para la creación, manipulación y visualización de mallas poligonales en dos y tres dimensiones.
  menu:
    main:
      - name: Noticias
        url: post
        weight: 20
      - name: Integrantes
        url: people
        weight: 30
      - name: Software-Lab
        url: project
        weight: 40
      - name: Posters-Diapositivas
        url: posters
        weight: 50
      - name: Publicaciones
        url: publication
        weight: 60
      - name: Proyectos
        url: fondecyts
        weight: 70
      - name: Ubicación
        url: location
        weight: 80

# Chinese language
zh:
  languageCode: zh
  languageName: "🇨🇳 中文"
  title: 应用科学网格划分实验室 (+Lab)
  params:
    description: 智利大学计算机科学系的+Lab实验室致力于研究和开发用于在二维和三维空间中创建、操纵和可视化多边形网格的算法和工具。
  menu:
    main:
      - name: 新闻
        url: post
        weight: 20
      - name: 团队成员
        url: people
        weight: 30
      - name: 实验室软件
        url: project
        weight: 40
      - name: 海报与幻灯片
        url: posters
        weight: 50
      - name: 发表论文
        url: publication
        weight: 60
      - name: 研究项目
        url: fondecyts
        weight: 70
      - name: 实验室地点
        url: location
        weight: 80
