services:
  hugo:
    build: .
    volumes:
      - .:/src:z
    # ports:
    #   - "1313:1313"
    environment:
      - HUGO_ENVIRONMENT=development
    # Forzamos el uso del binario hugo
    entrypoint: ["hugo"]
    command: ["--watch", "--minify", "--baseURL", "https://meshinglab.dcc.uchile.cl/"]