services:
  hugo:
    build: .
    container_name: meshing-hugo-live
    restart: always
    volumes:
      - .:/src:z
      - ../www:/src/public:z  # El link clave
    environment:
      - HUGO_ENVIRONMENT=development
    entrypoint: ["hugo"]
    command: ["--watch", "--poll", "100ms", "--minify", "--baseURL", "https://meshinglab.dcc.uchile.cl/"]

  git-cli:
    image: alpine/git
    container_name: meshing-git-cli
    volumes:
      - .:/src
      - ~/.ssh:/root/.ssh:ro
    working_dir: /src
    tty: true
    stdin_open: true
